### PR TITLE
Create Difficult things as beginner

### PR DESCRIPTION
**Pull request by Junho-Cho**

### CODE REVIEW

**Comment by eMBee** [comment]
this should not be a pull-request but at an issue though even better would be to ask your questions on the mailinglist. there people will be happy to help you: http://pike.lysator.liu.se/forums/

**Comment by poppa** [comment]
FYI: There's been a new version of the tutorial lying around since I re-made the Pike site a couple of months ago, but it never got installed on the production server. On the occasion of this pull request we'll make that happen asap so that the tutorial on the Pike site is usable.

**Comment by valgrind** [comment]
The introduction is still unreadable (unless you plan to do it on a 2001 flip mobile). Any progress on that?

**Comment by poppa** [comment]
We are working on the new solution, which is partly implemented on the Pike site server, but we ran into some minor oddities we need to sort out before it is working properly. But it's in the making...

**Comment by poppa** [comment]
Okey, there's a new fresh, readable, version of the Pike tutorial up on the site now. 
https://pike.lysator.liu.se/docs/tut/

**Pull request closed without merging**
